# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 390349b629979538ff78089cd6cf078483c60c29c46bb8b065f96ed22549e8c6a99b1c80a835dbddf3899df0e9fcd299274f85276cbee467206555898c667d55

test:
  secret_key_base: d57f40452785b5cde121a2c429ee3e1ef73549a886bb8f85acb62c8e3423bfeb8763916a89199562e9cb2764103de217aba63606686ddddb91363c1ffff84c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
